// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/gotd/bot/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gotd/bot/internal/ent/lastchannelmessage"
	"github.com/gotd/bot/internal/ent/prnotification"
	"github.com/gotd/bot/internal/ent/telegramaccount"
	"github.com/gotd/bot/internal/ent/telegramchannelstate"
	"github.com/gotd/bot/internal/ent/telegramsession"
	"github.com/gotd/bot/internal/ent/telegramuserstate"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// LastChannelMessage is the client for interacting with the LastChannelMessage builders.
	LastChannelMessage *LastChannelMessageClient
	// PRNotification is the client for interacting with the PRNotification builders.
	PRNotification *PRNotificationClient
	// TelegramAccount is the client for interacting with the TelegramAccount builders.
	TelegramAccount *TelegramAccountClient
	// TelegramChannelState is the client for interacting with the TelegramChannelState builders.
	TelegramChannelState *TelegramChannelStateClient
	// TelegramSession is the client for interacting with the TelegramSession builders.
	TelegramSession *TelegramSessionClient
	// TelegramUserState is the client for interacting with the TelegramUserState builders.
	TelegramUserState *TelegramUserStateClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.LastChannelMessage = NewLastChannelMessageClient(c.config)
	c.PRNotification = NewPRNotificationClient(c.config)
	c.TelegramAccount = NewTelegramAccountClient(c.config)
	c.TelegramChannelState = NewTelegramChannelStateClient(c.config)
	c.TelegramSession = NewTelegramSessionClient(c.config)
	c.TelegramUserState = NewTelegramUserStateClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		LastChannelMessage:   NewLastChannelMessageClient(cfg),
		PRNotification:       NewPRNotificationClient(cfg),
		TelegramAccount:      NewTelegramAccountClient(cfg),
		TelegramChannelState: NewTelegramChannelStateClient(cfg),
		TelegramSession:      NewTelegramSessionClient(cfg),
		TelegramUserState:    NewTelegramUserStateClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		LastChannelMessage:   NewLastChannelMessageClient(cfg),
		PRNotification:       NewPRNotificationClient(cfg),
		TelegramAccount:      NewTelegramAccountClient(cfg),
		TelegramChannelState: NewTelegramChannelStateClient(cfg),
		TelegramSession:      NewTelegramSessionClient(cfg),
		TelegramUserState:    NewTelegramUserStateClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		LastChannelMessage.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.LastChannelMessage, c.PRNotification, c.TelegramAccount,
		c.TelegramChannelState, c.TelegramSession, c.TelegramUserState,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.LastChannelMessage, c.PRNotification, c.TelegramAccount,
		c.TelegramChannelState, c.TelegramSession, c.TelegramUserState,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *LastChannelMessageMutation:
		return c.LastChannelMessage.mutate(ctx, m)
	case *PRNotificationMutation:
		return c.PRNotification.mutate(ctx, m)
	case *TelegramAccountMutation:
		return c.TelegramAccount.mutate(ctx, m)
	case *TelegramChannelStateMutation:
		return c.TelegramChannelState.mutate(ctx, m)
	case *TelegramSessionMutation:
		return c.TelegramSession.mutate(ctx, m)
	case *TelegramUserStateMutation:
		return c.TelegramUserState.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// LastChannelMessageClient is a client for the LastChannelMessage schema.
type LastChannelMessageClient struct {
	config
}

// NewLastChannelMessageClient returns a client for the LastChannelMessage from the given config.
func NewLastChannelMessageClient(c config) *LastChannelMessageClient {
	return &LastChannelMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lastchannelmessage.Hooks(f(g(h())))`.
func (c *LastChannelMessageClient) Use(hooks ...Hook) {
	c.hooks.LastChannelMessage = append(c.hooks.LastChannelMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `lastchannelmessage.Intercept(f(g(h())))`.
func (c *LastChannelMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.LastChannelMessage = append(c.inters.LastChannelMessage, interceptors...)
}

// Create returns a builder for creating a LastChannelMessage entity.
func (c *LastChannelMessageClient) Create() *LastChannelMessageCreate {
	mutation := newLastChannelMessageMutation(c.config, OpCreate)
	return &LastChannelMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LastChannelMessage entities.
func (c *LastChannelMessageClient) CreateBulk(builders ...*LastChannelMessageCreate) *LastChannelMessageCreateBulk {
	return &LastChannelMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *LastChannelMessageClient) MapCreateBulk(slice any, setFunc func(*LastChannelMessageCreate, int)) *LastChannelMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &LastChannelMessageCreateBulk{err: fmt.Errorf("calling to LastChannelMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*LastChannelMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &LastChannelMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LastChannelMessage.
func (c *LastChannelMessageClient) Update() *LastChannelMessageUpdate {
	mutation := newLastChannelMessageMutation(c.config, OpUpdate)
	return &LastChannelMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LastChannelMessageClient) UpdateOne(lcm *LastChannelMessage) *LastChannelMessageUpdateOne {
	mutation := newLastChannelMessageMutation(c.config, OpUpdateOne, withLastChannelMessage(lcm))
	return &LastChannelMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LastChannelMessageClient) UpdateOneID(id int64) *LastChannelMessageUpdateOne {
	mutation := newLastChannelMessageMutation(c.config, OpUpdateOne, withLastChannelMessageID(id))
	return &LastChannelMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LastChannelMessage.
func (c *LastChannelMessageClient) Delete() *LastChannelMessageDelete {
	mutation := newLastChannelMessageMutation(c.config, OpDelete)
	return &LastChannelMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *LastChannelMessageClient) DeleteOne(lcm *LastChannelMessage) *LastChannelMessageDeleteOne {
	return c.DeleteOneID(lcm.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *LastChannelMessageClient) DeleteOneID(id int64) *LastChannelMessageDeleteOne {
	builder := c.Delete().Where(lastchannelmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LastChannelMessageDeleteOne{builder}
}

// Query returns a query builder for LastChannelMessage.
func (c *LastChannelMessageClient) Query() *LastChannelMessageQuery {
	return &LastChannelMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeLastChannelMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a LastChannelMessage entity by its id.
func (c *LastChannelMessageClient) Get(ctx context.Context, id int64) (*LastChannelMessage, error) {
	return c.Query().Where(lastchannelmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LastChannelMessageClient) GetX(ctx context.Context, id int64) *LastChannelMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LastChannelMessageClient) Hooks() []Hook {
	return c.hooks.LastChannelMessage
}

// Interceptors returns the client interceptors.
func (c *LastChannelMessageClient) Interceptors() []Interceptor {
	return c.inters.LastChannelMessage
}

func (c *LastChannelMessageClient) mutate(ctx context.Context, m *LastChannelMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&LastChannelMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&LastChannelMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&LastChannelMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&LastChannelMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown LastChannelMessage mutation op: %q", m.Op())
	}
}

// PRNotificationClient is a client for the PRNotification schema.
type PRNotificationClient struct {
	config
}

// NewPRNotificationClient returns a client for the PRNotification from the given config.
func NewPRNotificationClient(c config) *PRNotificationClient {
	return &PRNotificationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `prnotification.Hooks(f(g(h())))`.
func (c *PRNotificationClient) Use(hooks ...Hook) {
	c.hooks.PRNotification = append(c.hooks.PRNotification, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `prnotification.Intercept(f(g(h())))`.
func (c *PRNotificationClient) Intercept(interceptors ...Interceptor) {
	c.inters.PRNotification = append(c.inters.PRNotification, interceptors...)
}

// Create returns a builder for creating a PRNotification entity.
func (c *PRNotificationClient) Create() *PRNotificationCreate {
	mutation := newPRNotificationMutation(c.config, OpCreate)
	return &PRNotificationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PRNotification entities.
func (c *PRNotificationClient) CreateBulk(builders ...*PRNotificationCreate) *PRNotificationCreateBulk {
	return &PRNotificationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PRNotificationClient) MapCreateBulk(slice any, setFunc func(*PRNotificationCreate, int)) *PRNotificationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PRNotificationCreateBulk{err: fmt.Errorf("calling to PRNotificationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PRNotificationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PRNotificationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PRNotification.
func (c *PRNotificationClient) Update() *PRNotificationUpdate {
	mutation := newPRNotificationMutation(c.config, OpUpdate)
	return &PRNotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PRNotificationClient) UpdateOne(pn *PRNotification) *PRNotificationUpdateOne {
	mutation := newPRNotificationMutation(c.config, OpUpdateOne, withPRNotification(pn))
	return &PRNotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PRNotificationClient) UpdateOneID(id int) *PRNotificationUpdateOne {
	mutation := newPRNotificationMutation(c.config, OpUpdateOne, withPRNotificationID(id))
	return &PRNotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PRNotification.
func (c *PRNotificationClient) Delete() *PRNotificationDelete {
	mutation := newPRNotificationMutation(c.config, OpDelete)
	return &PRNotificationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PRNotificationClient) DeleteOne(pn *PRNotification) *PRNotificationDeleteOne {
	return c.DeleteOneID(pn.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PRNotificationClient) DeleteOneID(id int) *PRNotificationDeleteOne {
	builder := c.Delete().Where(prnotification.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PRNotificationDeleteOne{builder}
}

// Query returns a query builder for PRNotification.
func (c *PRNotificationClient) Query() *PRNotificationQuery {
	return &PRNotificationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePRNotification},
		inters: c.Interceptors(),
	}
}

// Get returns a PRNotification entity by its id.
func (c *PRNotificationClient) Get(ctx context.Context, id int) (*PRNotification, error) {
	return c.Query().Where(prnotification.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PRNotificationClient) GetX(ctx context.Context, id int) *PRNotification {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PRNotificationClient) Hooks() []Hook {
	return c.hooks.PRNotification
}

// Interceptors returns the client interceptors.
func (c *PRNotificationClient) Interceptors() []Interceptor {
	return c.inters.PRNotification
}

func (c *PRNotificationClient) mutate(ctx context.Context, m *PRNotificationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PRNotificationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PRNotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PRNotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PRNotificationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PRNotification mutation op: %q", m.Op())
	}
}

// TelegramAccountClient is a client for the TelegramAccount schema.
type TelegramAccountClient struct {
	config
}

// NewTelegramAccountClient returns a client for the TelegramAccount from the given config.
func NewTelegramAccountClient(c config) *TelegramAccountClient {
	return &TelegramAccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `telegramaccount.Hooks(f(g(h())))`.
func (c *TelegramAccountClient) Use(hooks ...Hook) {
	c.hooks.TelegramAccount = append(c.hooks.TelegramAccount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `telegramaccount.Intercept(f(g(h())))`.
func (c *TelegramAccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.TelegramAccount = append(c.inters.TelegramAccount, interceptors...)
}

// Create returns a builder for creating a TelegramAccount entity.
func (c *TelegramAccountClient) Create() *TelegramAccountCreate {
	mutation := newTelegramAccountMutation(c.config, OpCreate)
	return &TelegramAccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TelegramAccount entities.
func (c *TelegramAccountClient) CreateBulk(builders ...*TelegramAccountCreate) *TelegramAccountCreateBulk {
	return &TelegramAccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TelegramAccountClient) MapCreateBulk(slice any, setFunc func(*TelegramAccountCreate, int)) *TelegramAccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TelegramAccountCreateBulk{err: fmt.Errorf("calling to TelegramAccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TelegramAccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TelegramAccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TelegramAccount.
func (c *TelegramAccountClient) Update() *TelegramAccountUpdate {
	mutation := newTelegramAccountMutation(c.config, OpUpdate)
	return &TelegramAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TelegramAccountClient) UpdateOne(ta *TelegramAccount) *TelegramAccountUpdateOne {
	mutation := newTelegramAccountMutation(c.config, OpUpdateOne, withTelegramAccount(ta))
	return &TelegramAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TelegramAccountClient) UpdateOneID(id string) *TelegramAccountUpdateOne {
	mutation := newTelegramAccountMutation(c.config, OpUpdateOne, withTelegramAccountID(id))
	return &TelegramAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TelegramAccount.
func (c *TelegramAccountClient) Delete() *TelegramAccountDelete {
	mutation := newTelegramAccountMutation(c.config, OpDelete)
	return &TelegramAccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TelegramAccountClient) DeleteOne(ta *TelegramAccount) *TelegramAccountDeleteOne {
	return c.DeleteOneID(ta.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TelegramAccountClient) DeleteOneID(id string) *TelegramAccountDeleteOne {
	builder := c.Delete().Where(telegramaccount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TelegramAccountDeleteOne{builder}
}

// Query returns a query builder for TelegramAccount.
func (c *TelegramAccountClient) Query() *TelegramAccountQuery {
	return &TelegramAccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTelegramAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a TelegramAccount entity by its id.
func (c *TelegramAccountClient) Get(ctx context.Context, id string) (*TelegramAccount, error) {
	return c.Query().Where(telegramaccount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TelegramAccountClient) GetX(ctx context.Context, id string) *TelegramAccount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TelegramAccountClient) Hooks() []Hook {
	return c.hooks.TelegramAccount
}

// Interceptors returns the client interceptors.
func (c *TelegramAccountClient) Interceptors() []Interceptor {
	return c.inters.TelegramAccount
}

func (c *TelegramAccountClient) mutate(ctx context.Context, m *TelegramAccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TelegramAccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TelegramAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TelegramAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TelegramAccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TelegramAccount mutation op: %q", m.Op())
	}
}

// TelegramChannelStateClient is a client for the TelegramChannelState schema.
type TelegramChannelStateClient struct {
	config
}

// NewTelegramChannelStateClient returns a client for the TelegramChannelState from the given config.
func NewTelegramChannelStateClient(c config) *TelegramChannelStateClient {
	return &TelegramChannelStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `telegramchannelstate.Hooks(f(g(h())))`.
func (c *TelegramChannelStateClient) Use(hooks ...Hook) {
	c.hooks.TelegramChannelState = append(c.hooks.TelegramChannelState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `telegramchannelstate.Intercept(f(g(h())))`.
func (c *TelegramChannelStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.TelegramChannelState = append(c.inters.TelegramChannelState, interceptors...)
}

// Create returns a builder for creating a TelegramChannelState entity.
func (c *TelegramChannelStateClient) Create() *TelegramChannelStateCreate {
	mutation := newTelegramChannelStateMutation(c.config, OpCreate)
	return &TelegramChannelStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TelegramChannelState entities.
func (c *TelegramChannelStateClient) CreateBulk(builders ...*TelegramChannelStateCreate) *TelegramChannelStateCreateBulk {
	return &TelegramChannelStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TelegramChannelStateClient) MapCreateBulk(slice any, setFunc func(*TelegramChannelStateCreate, int)) *TelegramChannelStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TelegramChannelStateCreateBulk{err: fmt.Errorf("calling to TelegramChannelStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TelegramChannelStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TelegramChannelStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TelegramChannelState.
func (c *TelegramChannelStateClient) Update() *TelegramChannelStateUpdate {
	mutation := newTelegramChannelStateMutation(c.config, OpUpdate)
	return &TelegramChannelStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TelegramChannelStateClient) UpdateOne(tcs *TelegramChannelState) *TelegramChannelStateUpdateOne {
	mutation := newTelegramChannelStateMutation(c.config, OpUpdateOne, withTelegramChannelState(tcs))
	return &TelegramChannelStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TelegramChannelStateClient) UpdateOneID(id int) *TelegramChannelStateUpdateOne {
	mutation := newTelegramChannelStateMutation(c.config, OpUpdateOne, withTelegramChannelStateID(id))
	return &TelegramChannelStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TelegramChannelState.
func (c *TelegramChannelStateClient) Delete() *TelegramChannelStateDelete {
	mutation := newTelegramChannelStateMutation(c.config, OpDelete)
	return &TelegramChannelStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TelegramChannelStateClient) DeleteOne(tcs *TelegramChannelState) *TelegramChannelStateDeleteOne {
	return c.DeleteOneID(tcs.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TelegramChannelStateClient) DeleteOneID(id int) *TelegramChannelStateDeleteOne {
	builder := c.Delete().Where(telegramchannelstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TelegramChannelStateDeleteOne{builder}
}

// Query returns a query builder for TelegramChannelState.
func (c *TelegramChannelStateClient) Query() *TelegramChannelStateQuery {
	return &TelegramChannelStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTelegramChannelState},
		inters: c.Interceptors(),
	}
}

// Get returns a TelegramChannelState entity by its id.
func (c *TelegramChannelStateClient) Get(ctx context.Context, id int) (*TelegramChannelState, error) {
	return c.Query().Where(telegramchannelstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TelegramChannelStateClient) GetX(ctx context.Context, id int) *TelegramChannelState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a TelegramChannelState.
func (c *TelegramChannelStateClient) QueryUser(tcs *TelegramChannelState) *TelegramUserStateQuery {
	query := (&TelegramUserStateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := tcs.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(telegramchannelstate.Table, telegramchannelstate.FieldID, id),
			sqlgraph.To(telegramuserstate.Table, telegramuserstate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, telegramchannelstate.UserTable, telegramchannelstate.UserColumn),
		)
		fromV = sqlgraph.Neighbors(tcs.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TelegramChannelStateClient) Hooks() []Hook {
	return c.hooks.TelegramChannelState
}

// Interceptors returns the client interceptors.
func (c *TelegramChannelStateClient) Interceptors() []Interceptor {
	return c.inters.TelegramChannelState
}

func (c *TelegramChannelStateClient) mutate(ctx context.Context, m *TelegramChannelStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TelegramChannelStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TelegramChannelStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TelegramChannelStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TelegramChannelStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TelegramChannelState mutation op: %q", m.Op())
	}
}

// TelegramSessionClient is a client for the TelegramSession schema.
type TelegramSessionClient struct {
	config
}

// NewTelegramSessionClient returns a client for the TelegramSession from the given config.
func NewTelegramSessionClient(c config) *TelegramSessionClient {
	return &TelegramSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `telegramsession.Hooks(f(g(h())))`.
func (c *TelegramSessionClient) Use(hooks ...Hook) {
	c.hooks.TelegramSession = append(c.hooks.TelegramSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `telegramsession.Intercept(f(g(h())))`.
func (c *TelegramSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.TelegramSession = append(c.inters.TelegramSession, interceptors...)
}

// Create returns a builder for creating a TelegramSession entity.
func (c *TelegramSessionClient) Create() *TelegramSessionCreate {
	mutation := newTelegramSessionMutation(c.config, OpCreate)
	return &TelegramSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TelegramSession entities.
func (c *TelegramSessionClient) CreateBulk(builders ...*TelegramSessionCreate) *TelegramSessionCreateBulk {
	return &TelegramSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TelegramSessionClient) MapCreateBulk(slice any, setFunc func(*TelegramSessionCreate, int)) *TelegramSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TelegramSessionCreateBulk{err: fmt.Errorf("calling to TelegramSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TelegramSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TelegramSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TelegramSession.
func (c *TelegramSessionClient) Update() *TelegramSessionUpdate {
	mutation := newTelegramSessionMutation(c.config, OpUpdate)
	return &TelegramSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TelegramSessionClient) UpdateOne(ts *TelegramSession) *TelegramSessionUpdateOne {
	mutation := newTelegramSessionMutation(c.config, OpUpdateOne, withTelegramSession(ts))
	return &TelegramSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TelegramSessionClient) UpdateOneID(id uuid.UUID) *TelegramSessionUpdateOne {
	mutation := newTelegramSessionMutation(c.config, OpUpdateOne, withTelegramSessionID(id))
	return &TelegramSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TelegramSession.
func (c *TelegramSessionClient) Delete() *TelegramSessionDelete {
	mutation := newTelegramSessionMutation(c.config, OpDelete)
	return &TelegramSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TelegramSessionClient) DeleteOne(ts *TelegramSession) *TelegramSessionDeleteOne {
	return c.DeleteOneID(ts.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TelegramSessionClient) DeleteOneID(id uuid.UUID) *TelegramSessionDeleteOne {
	builder := c.Delete().Where(telegramsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TelegramSessionDeleteOne{builder}
}

// Query returns a query builder for TelegramSession.
func (c *TelegramSessionClient) Query() *TelegramSessionQuery {
	return &TelegramSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTelegramSession},
		inters: c.Interceptors(),
	}
}

// Get returns a TelegramSession entity by its id.
func (c *TelegramSessionClient) Get(ctx context.Context, id uuid.UUID) (*TelegramSession, error) {
	return c.Query().Where(telegramsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TelegramSessionClient) GetX(ctx context.Context, id uuid.UUID) *TelegramSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TelegramSessionClient) Hooks() []Hook {
	return c.hooks.TelegramSession
}

// Interceptors returns the client interceptors.
func (c *TelegramSessionClient) Interceptors() []Interceptor {
	return c.inters.TelegramSession
}

func (c *TelegramSessionClient) mutate(ctx context.Context, m *TelegramSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TelegramSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TelegramSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TelegramSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TelegramSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TelegramSession mutation op: %q", m.Op())
	}
}

// TelegramUserStateClient is a client for the TelegramUserState schema.
type TelegramUserStateClient struct {
	config
}

// NewTelegramUserStateClient returns a client for the TelegramUserState from the given config.
func NewTelegramUserStateClient(c config) *TelegramUserStateClient {
	return &TelegramUserStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `telegramuserstate.Hooks(f(g(h())))`.
func (c *TelegramUserStateClient) Use(hooks ...Hook) {
	c.hooks.TelegramUserState = append(c.hooks.TelegramUserState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `telegramuserstate.Intercept(f(g(h())))`.
func (c *TelegramUserStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.TelegramUserState = append(c.inters.TelegramUserState, interceptors...)
}

// Create returns a builder for creating a TelegramUserState entity.
func (c *TelegramUserStateClient) Create() *TelegramUserStateCreate {
	mutation := newTelegramUserStateMutation(c.config, OpCreate)
	return &TelegramUserStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TelegramUserState entities.
func (c *TelegramUserStateClient) CreateBulk(builders ...*TelegramUserStateCreate) *TelegramUserStateCreateBulk {
	return &TelegramUserStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TelegramUserStateClient) MapCreateBulk(slice any, setFunc func(*TelegramUserStateCreate, int)) *TelegramUserStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TelegramUserStateCreateBulk{err: fmt.Errorf("calling to TelegramUserStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TelegramUserStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TelegramUserStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TelegramUserState.
func (c *TelegramUserStateClient) Update() *TelegramUserStateUpdate {
	mutation := newTelegramUserStateMutation(c.config, OpUpdate)
	return &TelegramUserStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TelegramUserStateClient) UpdateOne(tus *TelegramUserState) *TelegramUserStateUpdateOne {
	mutation := newTelegramUserStateMutation(c.config, OpUpdateOne, withTelegramUserState(tus))
	return &TelegramUserStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TelegramUserStateClient) UpdateOneID(id int64) *TelegramUserStateUpdateOne {
	mutation := newTelegramUserStateMutation(c.config, OpUpdateOne, withTelegramUserStateID(id))
	return &TelegramUserStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TelegramUserState.
func (c *TelegramUserStateClient) Delete() *TelegramUserStateDelete {
	mutation := newTelegramUserStateMutation(c.config, OpDelete)
	return &TelegramUserStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TelegramUserStateClient) DeleteOne(tus *TelegramUserState) *TelegramUserStateDeleteOne {
	return c.DeleteOneID(tus.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TelegramUserStateClient) DeleteOneID(id int64) *TelegramUserStateDeleteOne {
	builder := c.Delete().Where(telegramuserstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TelegramUserStateDeleteOne{builder}
}

// Query returns a query builder for TelegramUserState.
func (c *TelegramUserStateClient) Query() *TelegramUserStateQuery {
	return &TelegramUserStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTelegramUserState},
		inters: c.Interceptors(),
	}
}

// Get returns a TelegramUserState entity by its id.
func (c *TelegramUserStateClient) Get(ctx context.Context, id int64) (*TelegramUserState, error) {
	return c.Query().Where(telegramuserstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TelegramUserStateClient) GetX(ctx context.Context, id int64) *TelegramUserState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannels queries the channels edge of a TelegramUserState.
func (c *TelegramUserStateClient) QueryChannels(tus *TelegramUserState) *TelegramChannelStateQuery {
	query := (&TelegramChannelStateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := tus.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(telegramuserstate.Table, telegramuserstate.FieldID, id),
			sqlgraph.To(telegramchannelstate.Table, telegramchannelstate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, telegramuserstate.ChannelsTable, telegramuserstate.ChannelsColumn),
		)
		fromV = sqlgraph.Neighbors(tus.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TelegramUserStateClient) Hooks() []Hook {
	return c.hooks.TelegramUserState
}

// Interceptors returns the client interceptors.
func (c *TelegramUserStateClient) Interceptors() []Interceptor {
	return c.inters.TelegramUserState
}

func (c *TelegramUserStateClient) mutate(ctx context.Context, m *TelegramUserStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TelegramUserStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TelegramUserStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TelegramUserStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TelegramUserStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TelegramUserState mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		LastChannelMessage, PRNotification, TelegramAccount, TelegramChannelState,
		TelegramSession, TelegramUserState []ent.Hook
	}
	inters struct {
		LastChannelMessage, PRNotification, TelegramAccount, TelegramChannelState,
		TelegramSession, TelegramUserState []ent.Interceptor
	}
)
