// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gotd/bot/internal/ent/predicate"
	"github.com/gotd/bot/internal/ent/telegramaccount"
)

// TelegramAccountDelete is the builder for deleting a TelegramAccount entity.
type TelegramAccountDelete struct {
	config
	hooks    []Hook
	mutation *TelegramAccountMutation
}

// Where appends a list predicates to the TelegramAccountDelete builder.
func (tad *TelegramAccountDelete) Where(ps ...predicate.TelegramAccount) *TelegramAccountDelete {
	tad.mutation.Where(ps...)
	return tad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tad *TelegramAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tad.sqlExec, tad.mutation, tad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tad *TelegramAccountDelete) ExecX(ctx context.Context) int {
	n, err := tad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tad *TelegramAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(telegramaccount.Table, sqlgraph.NewFieldSpec(telegramaccount.FieldID, field.TypeString))
	if ps := tad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tad.mutation.done = true
	return affected, err
}

// TelegramAccountDeleteOne is the builder for deleting a single TelegramAccount entity.
type TelegramAccountDeleteOne struct {
	tad *TelegramAccountDelete
}

// Where appends a list predicates to the TelegramAccountDelete builder.
func (tado *TelegramAccountDeleteOne) Where(ps ...predicate.TelegramAccount) *TelegramAccountDeleteOne {
	tado.tad.mutation.Where(ps...)
	return tado
}

// Exec executes the deletion query.
func (tado *TelegramAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := tado.tad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{telegramaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tado *TelegramAccountDeleteOne) ExecX(ctx context.Context) {
	if err := tado.Exec(ctx); err != nil {
		panic(err)
	}
}
