// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gotd/bot/internal/ent/predicate"
	"github.com/gotd/bot/internal/ent/telegramaccount"
)

// TelegramAccountQuery is the builder for querying TelegramAccount entities.
type TelegramAccountQuery struct {
	config
	ctx        *QueryContext
	order      []telegramaccount.OrderOption
	inters     []Interceptor
	predicates []predicate.TelegramAccount
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TelegramAccountQuery builder.
func (taq *TelegramAccountQuery) Where(ps ...predicate.TelegramAccount) *TelegramAccountQuery {
	taq.predicates = append(taq.predicates, ps...)
	return taq
}

// Limit the number of records to be returned by this query.
func (taq *TelegramAccountQuery) Limit(limit int) *TelegramAccountQuery {
	taq.ctx.Limit = &limit
	return taq
}

// Offset to start from.
func (taq *TelegramAccountQuery) Offset(offset int) *TelegramAccountQuery {
	taq.ctx.Offset = &offset
	return taq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (taq *TelegramAccountQuery) Unique(unique bool) *TelegramAccountQuery {
	taq.ctx.Unique = &unique
	return taq
}

// Order specifies how the records should be ordered.
func (taq *TelegramAccountQuery) Order(o ...telegramaccount.OrderOption) *TelegramAccountQuery {
	taq.order = append(taq.order, o...)
	return taq
}

// First returns the first TelegramAccount entity from the query.
// Returns a *NotFoundError when no TelegramAccount was found.
func (taq *TelegramAccountQuery) First(ctx context.Context) (*TelegramAccount, error) {
	nodes, err := taq.Limit(1).All(setContextOp(ctx, taq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{telegramaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (taq *TelegramAccountQuery) FirstX(ctx context.Context) *TelegramAccount {
	node, err := taq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TelegramAccount ID from the query.
// Returns a *NotFoundError when no TelegramAccount ID was found.
func (taq *TelegramAccountQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = taq.Limit(1).IDs(setContextOp(ctx, taq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{telegramaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (taq *TelegramAccountQuery) FirstIDX(ctx context.Context) string {
	id, err := taq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TelegramAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TelegramAccount entity is found.
// Returns a *NotFoundError when no TelegramAccount entities are found.
func (taq *TelegramAccountQuery) Only(ctx context.Context) (*TelegramAccount, error) {
	nodes, err := taq.Limit(2).All(setContextOp(ctx, taq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{telegramaccount.Label}
	default:
		return nil, &NotSingularError{telegramaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (taq *TelegramAccountQuery) OnlyX(ctx context.Context) *TelegramAccount {
	node, err := taq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TelegramAccount ID in the query.
// Returns a *NotSingularError when more than one TelegramAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (taq *TelegramAccountQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = taq.Limit(2).IDs(setContextOp(ctx, taq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{telegramaccount.Label}
	default:
		err = &NotSingularError{telegramaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (taq *TelegramAccountQuery) OnlyIDX(ctx context.Context) string {
	id, err := taq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TelegramAccounts.
func (taq *TelegramAccountQuery) All(ctx context.Context) ([]*TelegramAccount, error) {
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryAll)
	if err := taq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TelegramAccount, *TelegramAccountQuery]()
	return withInterceptors[[]*TelegramAccount](ctx, taq, qr, taq.inters)
}

// AllX is like All, but panics if an error occurs.
func (taq *TelegramAccountQuery) AllX(ctx context.Context) []*TelegramAccount {
	nodes, err := taq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TelegramAccount IDs.
func (taq *TelegramAccountQuery) IDs(ctx context.Context) (ids []string, err error) {
	if taq.ctx.Unique == nil && taq.path != nil {
		taq.Unique(true)
	}
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryIDs)
	if err = taq.Select(telegramaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (taq *TelegramAccountQuery) IDsX(ctx context.Context) []string {
	ids, err := taq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (taq *TelegramAccountQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryCount)
	if err := taq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, taq, querierCount[*TelegramAccountQuery](), taq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (taq *TelegramAccountQuery) CountX(ctx context.Context) int {
	count, err := taq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (taq *TelegramAccountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryExist)
	switch _, err := taq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (taq *TelegramAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := taq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TelegramAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (taq *TelegramAccountQuery) Clone() *TelegramAccountQuery {
	if taq == nil {
		return nil
	}
	return &TelegramAccountQuery{
		config:     taq.config,
		ctx:        taq.ctx.Clone(),
		order:      append([]telegramaccount.OrderOption{}, taq.order...),
		inters:     append([]Interceptor{}, taq.inters...),
		predicates: append([]predicate.TelegramAccount{}, taq.predicates...),
		// clone intermediate query.
		sql:  taq.sql.Clone(),
		path: taq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TelegramAccount.Query().
//		GroupBy(telegramaccount.FieldCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (taq *TelegramAccountQuery) GroupBy(field string, fields ...string) *TelegramAccountGroupBy {
	taq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TelegramAccountGroupBy{build: taq}
	grbuild.flds = &taq.ctx.Fields
	grbuild.label = telegramaccount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Code string `json:"code,omitempty"`
//	}
//
//	client.TelegramAccount.Query().
//		Select(telegramaccount.FieldCode).
//		Scan(ctx, &v)
func (taq *TelegramAccountQuery) Select(fields ...string) *TelegramAccountSelect {
	taq.ctx.Fields = append(taq.ctx.Fields, fields...)
	sbuild := &TelegramAccountSelect{TelegramAccountQuery: taq}
	sbuild.label = telegramaccount.Label
	sbuild.flds, sbuild.scan = &taq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TelegramAccountSelect configured with the given aggregations.
func (taq *TelegramAccountQuery) Aggregate(fns ...AggregateFunc) *TelegramAccountSelect {
	return taq.Select().Aggregate(fns...)
}

func (taq *TelegramAccountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range taq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, taq); err != nil {
				return err
			}
		}
	}
	for _, f := range taq.ctx.Fields {
		if !telegramaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if taq.path != nil {
		prev, err := taq.path(ctx)
		if err != nil {
			return err
		}
		taq.sql = prev
	}
	return nil
}

func (taq *TelegramAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TelegramAccount, error) {
	var (
		nodes = []*TelegramAccount{}
		_spec = taq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TelegramAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TelegramAccount{config: taq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, taq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (taq *TelegramAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := taq.querySpec()
	_spec.Node.Columns = taq.ctx.Fields
	if len(taq.ctx.Fields) > 0 {
		_spec.Unique = taq.ctx.Unique != nil && *taq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, taq.driver, _spec)
}

func (taq *TelegramAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(telegramaccount.Table, telegramaccount.Columns, sqlgraph.NewFieldSpec(telegramaccount.FieldID, field.TypeString))
	_spec.From = taq.sql
	if unique := taq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if taq.path != nil {
		_spec.Unique = true
	}
	if fields := taq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, telegramaccount.FieldID)
		for i := range fields {
			if fields[i] != telegramaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := taq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := taq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := taq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := taq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (taq *TelegramAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(taq.driver.Dialect())
	t1 := builder.Table(telegramaccount.Table)
	columns := taq.ctx.Fields
	if len(columns) == 0 {
		columns = telegramaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if taq.sql != nil {
		selector = taq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if taq.ctx.Unique != nil && *taq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range taq.predicates {
		p(selector)
	}
	for _, p := range taq.order {
		p(selector)
	}
	if offset := taq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := taq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TelegramAccountGroupBy is the group-by builder for TelegramAccount entities.
type TelegramAccountGroupBy struct {
	selector
	build *TelegramAccountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tagb *TelegramAccountGroupBy) Aggregate(fns ...AggregateFunc) *TelegramAccountGroupBy {
	tagb.fns = append(tagb.fns, fns...)
	return tagb
}

// Scan applies the selector query and scans the result into the given value.
func (tagb *TelegramAccountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tagb.build.ctx, ent.OpQueryGroupBy)
	if err := tagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TelegramAccountQuery, *TelegramAccountGroupBy](ctx, tagb.build, tagb, tagb.build.inters, v)
}

func (tagb *TelegramAccountGroupBy) sqlScan(ctx context.Context, root *TelegramAccountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tagb.fns))
	for _, fn := range tagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tagb.flds)+len(tagb.fns))
		for _, f := range *tagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TelegramAccountSelect is the builder for selecting fields of TelegramAccount entities.
type TelegramAccountSelect struct {
	*TelegramAccountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tas *TelegramAccountSelect) Aggregate(fns ...AggregateFunc) *TelegramAccountSelect {
	tas.fns = append(tas.fns, fns...)
	return tas
}

// Scan applies the selector query and scans the result into the given value.
func (tas *TelegramAccountSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tas.ctx, ent.OpQuerySelect)
	if err := tas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TelegramAccountQuery, *TelegramAccountSelect](ctx, tas.TelegramAccountQuery, tas, tas.inters, v)
}

func (tas *TelegramAccountSelect) sqlScan(ctx context.Context, root *TelegramAccountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tas.fns))
	for _, fn := range tas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
