-- Create "last_channel_messages" table
CREATE TABLE "last_channel_messages" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "message_id" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create "pr_notifications" table
CREATE TABLE "pr_notifications" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "repo_id" bigint NOT NULL, "pull_request_id" bigint NOT NULL, "pull_request_title" character varying NOT NULL DEFAULT '', "pull_request_body" character varying NOT NULL DEFAULT '', "pull_request_author_login" character varying NOT NULL DEFAULT '', "message_id" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "prnotification_repo_id_pull_request_id" to table: "pr_notifications"
CREATE UNIQUE INDEX "prnotification_repo_id_pull_request_id" ON "pr_notifications" ("repo_id", "pull_request_id");
-- Create "telegram_sessions" table
CREATE TABLE "telegram_sessions" ("id" uuid NOT NULL, "data" bytea NOT NULL, PRIMARY KEY ("id"));
-- Create "telegram_user_states" table
CREATE TABLE "telegram_user_states" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "qts" bigint NOT NULL DEFAULT 0, "pts" bigint NOT NULL DEFAULT 0, "date" bigint NOT NULL DEFAULT 0, "seq" bigint NOT NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "telegram_channel_states" table
CREATE TABLE "telegram_channel_states" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "channel_id" bigint NOT NULL, "pts" bigint NOT NULL DEFAULT 0, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "telegram_channel_states_telegram_user_states_channels" FOREIGN KEY ("user_id") REFERENCES "telegram_user_states" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "telegramchannelstate_user_id_channel_id" to table: "telegram_channel_states"
CREATE UNIQUE INDEX "telegramchannelstate_user_id_channel_id" ON "telegram_channel_states" ("user_id", "channel_id");
