// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AcquireTelegramAccount implements acquireTelegramAccount operation.
//
// Acquire telegram account.
//
// POST /telegram/account/acquire
func (UnimplementedHandler) AcquireTelegramAccount(ctx context.Context) (r *AcquireTelegramAccountOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTelegramAccount implements createTelegramAccount operation.
//
// Create telegram account.
//
// POST /telegram/account/create
func (UnimplementedHandler) CreateTelegramAccount(ctx context.Context, req *CreateTelegramAccountReq) (r *CreateTelegramAccountOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Get health.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// HeartbeatTelegramAccount implements heartbeatTelegramAccount operation.
//
// Heartbeat telegram account.
//
// GET /telegram/account/heartbeat/{token}
func (UnimplementedHandler) HeartbeatTelegramAccount(ctx context.Context, params HeartbeatTelegramAccountParams) (r *HeartbeatTelegramAccountOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ReceiveTelegramCode implements receiveTelegramCode operation.
//
// Receive telegram code.
//
// GET /telegram/code/receive/{token}
func (UnimplementedHandler) ReceiveTelegramCode(ctx context.Context, params ReceiveTelegramCodeParams) (r *ReceiveTelegramCodeOK, _ error) {
	return r, ht.ErrNotImplemented
}

// SetTelegramAccountCode implements setTelegramAccountCode operation.
//
// Set telegram account code.
//
// POST /telegram/account/{id}/set_code
func (UnimplementedHandler) SetTelegramAccountCode(ctx context.Context, req *SetTelegramAccountCodeReq, params SetTelegramAccountCodeParams) (r *SetTelegramAccountCodeOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
