// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AcquireTelegramAccount implements acquireTelegramAccount operation.
//
// Acquire telegram account.
//
// POST /api/telegram/account/acquire
func (UnimplementedHandler) AcquireTelegramAccount(ctx context.Context, req *AcquireTelegramAccountReq) (r *AcquireTelegramAccountOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Get health.
//
// GET /api/health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// HeartbeatTelegramAccount implements heartbeatTelegramAccount operation.
//
// Heartbeat telegram account.
//
// GET /api/telegram/account/heartbeat/{token}
func (UnimplementedHandler) HeartbeatTelegramAccount(ctx context.Context, params HeartbeatTelegramAccountParams) error {
	return ht.ErrNotImplemented
}

// ReceiveTelegramCode implements receiveTelegramCode operation.
//
// Receive telegram code.
//
// GET /api/telegram/code/receive/{token}
func (UnimplementedHandler) ReceiveTelegramCode(ctx context.Context, params ReceiveTelegramCodeParams) (r *ReceiveTelegramCodeOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
