// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateTelegramAccount implements createTelegramAccount operation.
	//
	// Create telegram account.
	//
	// POST /telegram/account/create
	CreateTelegramAccount(ctx context.Context, req *CreateTelegramAccountReq) (*CreateTelegramAccountOK, error)
	// GetHealth implements getHealth operation.
	//
	// Get health.
	//
	// GET /health
	GetHealth(ctx context.Context) (*Health, error)
	// SetTelegramAccountCode implements setTelegramAccountCode operation.
	//
	// Set telegram account code.
	//
	// POST /telegram/account/{id}/set_code
	SetTelegramAccountCode(ctx context.Context, req *SetTelegramAccountCodeReq, params SetTelegramAccountCodeParams) (*SetTelegramAccountCodeOK, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
