// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type CreateTelegramAccountOK struct {
	AccountID TelegramAccountID `json:"account_id"`
}

// GetAccountID returns the value of AccountID.
func (s *CreateTelegramAccountOK) GetAccountID() TelegramAccountID {
	return s.AccountID
}

// SetAccountID sets the value of AccountID.
func (s *CreateTelegramAccountOK) SetAccountID(val TelegramAccountID) {
	s.AccountID = val
}

type CreateTelegramAccountReq struct {
	PhoneNumber TelegramAccountID `json:"phone_number"`
}

// GetPhoneNumber returns the value of PhoneNumber.
func (s *CreateTelegramAccountReq) GetPhoneNumber() TelegramAccountID {
	return s.PhoneNumber
}

// SetPhoneNumber sets the value of PhoneNumber.
func (s *CreateTelegramAccountReq) SetPhoneNumber(val TelegramAccountID) {
	s.PhoneNumber = val
}

// Error occurred while processing request.
// Ref: #/components/schemas/Error
type Error struct {
	// Human-readable error message.
	ErrorMessage string     `json:"error_message"`
	TraceID      OptTraceID `json:"trace_id"`
	SpanID       OptSpanID  `json:"span_id"`
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *Error) GetErrorMessage() string {
	return s.ErrorMessage
}

// GetTraceID returns the value of TraceID.
func (s *Error) GetTraceID() OptTraceID {
	return s.TraceID
}

// GetSpanID returns the value of SpanID.
func (s *Error) GetSpanID() OptSpanID {
	return s.SpanID
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *Error) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

// SetTraceID sets the value of TraceID.
func (s *Error) SetTraceID(val OptTraceID) {
	s.TraceID = val
}

// SetSpanID sets the value of SpanID.
func (s *Error) SetSpanID(val OptSpanID) {
	s.SpanID = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/Health
type Health struct {
	// Health status.
	Status string `json:"status"`
	// Service version.
	Version string `json:"version"`
	// Service commit.
	Commit string `json:"commit"`
	// Service build date.
	BuildDate time.Time `json:"build_date"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() string {
	return s.Status
}

// GetVersion returns the value of Version.
func (s *Health) GetVersion() string {
	return s.Version
}

// GetCommit returns the value of Commit.
func (s *Health) GetCommit() string {
	return s.Commit
}

// GetBuildDate returns the value of BuildDate.
func (s *Health) GetBuildDate() time.Time {
	return s.BuildDate
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val string) {
	s.Status = val
}

// SetVersion sets the value of Version.
func (s *Health) SetVersion(val string) {
	s.Version = val
}

// SetCommit sets the value of Commit.
func (s *Health) SetCommit(val string) {
	s.Commit = val
}

// SetBuildDate sets the value of BuildDate.
func (s *Health) SetBuildDate(val time.Time) {
	s.BuildDate = val
}

// NewOptSpanID returns new OptSpanID with value set to v.
func NewOptSpanID(v SpanID) OptSpanID {
	return OptSpanID{
		Value: v,
		Set:   true,
	}
}

// OptSpanID is optional SpanID.
type OptSpanID struct {
	Value SpanID
	Set   bool
}

// IsSet returns true if OptSpanID was set.
func (o OptSpanID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSpanID) Reset() {
	var v SpanID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSpanID) SetTo(v SpanID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSpanID) Get() (v SpanID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSpanID) Or(d SpanID) SpanID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTraceID returns new OptTraceID with value set to v.
func NewOptTraceID(v TraceID) OptTraceID {
	return OptTraceID{
		Value: v,
		Set:   true,
	}
}

// OptTraceID is optional TraceID.
type OptTraceID struct {
	Value TraceID
	Set   bool
}

// IsSet returns true if OptTraceID was set.
func (o OptTraceID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTraceID) Reset() {
	var v TraceID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTraceID) SetTo(v TraceID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTraceID) Get() (v TraceID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTraceID) Or(d TraceID) TraceID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type SetTelegramAccountCodeOK struct {
	AccountID TelegramAccountID `json:"account_id"`
}

// GetAccountID returns the value of AccountID.
func (s *SetTelegramAccountCodeOK) GetAccountID() TelegramAccountID {
	return s.AccountID
}

// SetAccountID sets the value of AccountID.
func (s *SetTelegramAccountCodeOK) SetAccountID(val TelegramAccountID) {
	s.AccountID = val
}

type SetTelegramAccountCodeReq struct {
	// Code.
	Code string `json:"code"`
}

// GetCode returns the value of Code.
func (s *SetTelegramAccountCodeReq) GetCode() string {
	return s.Code
}

// SetCode sets the value of Code.
func (s *SetTelegramAccountCodeReq) SetCode(val string) {
	s.Code = val
}

type SpanID string

type TelegramAccountID string

type TokenAuth struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s *TokenAuth) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *TokenAuth) SetAPIKey(val string) {
	s.APIKey = val
}

type TraceID string
