// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateTelegramAccountOperation  OperationName = "CreateTelegramAccount"
	GetHealthOperation              OperationName = "GetHealth"
	SetTelegramAccountCodeOperation OperationName = "SetTelegramAccountCode"
)
